### ISSUE TITLE
Error calling 'update-all-autoloads'

### ISSUE THREAD

**Issue by srustamo** [abo-abo/oremacs#10]
There is no error calling 'update-all-autoloads' after manually installing (with C-x-e), but autoloaded call gives the error.

auto.el is in the root of the cloned git dir.

Trace:
Debugger entered--Lisp error: (file-error "Cannot open load file" "Not a directory" "auto")
  autoload-do-load((autoload "auto" "\n\n(fn)" t nil) update-all-autoloads)
  command-execute(update-all-autoloads record)
  #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"]("update-all-autoloads")
  ivy-call()
  ivy-read("M-x " ("toggle-debug-on-error" "package-list-packages" "ag" "edebug-defun" "eval-defun" "update-file-autoloads" "counsel-org-tag" "org-pomodoro" "customize-group" "dired" "eval-buffer" "join-line" "package-list-packages-no-fetch" "evil-mode" "wcheck-actions" "magit-diff" "load-theme" "helm-swoop" "customize-themes" "eval-region" "magit-status" "orgstruct-mode" "toggle-fullscreen" "interleave" "wcheck-mode" "wcheck-jump-forward" "persp-switch" "paradox-list-packages" "company-mode" "package-install" "diff-buffer-with-file" "customize-face" "helm-dash" "airline-themes-set-modeline" "visual-line-mode" "org-mode" "flyspell-mode" "benchmark-init/show-durations-tabulated" "flyspell-buffer" "flyspell-correct-word-before-point" "linum-mode" "ispell-buffer" "open-file-at-cursor" "ispell-change-dictionary" "org-pandoc-export-to-docx" "describe-font" "magit-version" "whitespace-mode" "mac-font-panel-mode" "counsel-ag" ...) :predicate nil :require-match t :history extended-command-history :action #[257 "\304\305!\203\f\306\307!!\210\307!\211\310\307!\311\")\207" [current-prefix-arg prefix-arg this-command real-this-command featurep smex smex-rank intern command-execute record] 4 "\n\n(fn CMD)"] :sort nil :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input "^" :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)

**Comment by abo-abo** [comment]
Remove `loaddefs.el`, restart, and <kbd>M-x</kbd> `update-all-autoloads`.

**Comment by abo-abo** [comment]
Maybe not remove, just make it empty.

**Comment by srustamo** [comment]
Still get this error after emptying loaddefs.el

 Incidentally, moving the whole 'defun' for `update-all-autoloads' to init.el complete with ###autoload cookie and updating autoloads, (init.el is in the same dir as auto.el) does not produce this error.

Also, adding any other function to auto.el with ###autolaod cookie and updating loaddefs.el also produces subject error.

**Comment by abo-abo** [comment]
Can you reproduce with `git clone`? I could fix the error if I could reproduce it too.

**Comment by srustamo** [comment]
Let me close this issue, I'll reopen when have a bit more time to tinker with this.

**Comment by srustamo** [comment]
It looks like the root of the config defined in `emacs-d` is not in the `load-path`.

It also explains why moving defun for `update-all-autoloads` to `init.el` does not produce the subject error, since `init.el` is explicitly loaded by `load` in the `.emacs` in homdir.

Maybe you are adding `emacs-d` somehow to the `load-path`, but I could not find where grepping your config.

**Comment by srustamo** [comment]
Adding `(add-to-list 'load-path (expand-file-name emacs-d))` in `init.el` removes the error.

**Comment by abo-abo** [comment]
> Maybe you are adding emacs-d somehow to the load-path, but I could not find where grepping your config.

It's added here: https://github.com/abo-abo/oremacs/blob/github/init.el#L15.

**Comment by srustamo** [comment]
Thank you.
