### ISSUE TITLE
dired-omit-files regex

### ISSUE THREAD

**Issue by srustamo** [abo-abo/oremacs#15]
I think I understand the intention of this regex below. It looks for for files in dired, which:

- start with one ore more '.' (first grouping)
- have 'aux' or 'log' etc after the first grouping
- or compile_commands.json
- or '__pycache__'

If it is so, it does not seem to work on `.log' files. 

Is my understanding correct? Or does this regex do something else?

```
(setq dired-omit-files "\\(?:.*\\.\\(?:aux\\|log\\|pickle\\|synctex\\.gz\\|run\\.xml\\|bcf\\|am\\|in\\|blx\\.bib\\)\\'\\)\\|compile_commands.json\\|__pycache__")
```

**Comment by srustamo** [comment]
This line is from [here](https://github.com/abo-abo/oremacs/blob/github/modes/ora-dired.el#L13)

**Comment by srustamo** [comment]
Looks like I have the old version of this file, still, could you please explain the old regex?

**Comment by abo-abo** [comment]
Dot followed by one of the extensions in the group is omitted. Works on log files too.

**Comment by srustamo** [comment]
Why not use `dired-omit-extensions` from diredx package, which you require on the top of the file?

**Comment by abo-abo** [comment]
It's more flexible, see `dired-omit-regexp` function.

**Comment by srustamo** [comment]
By default, `dired-omit-extensions` seems to contain many extensions. Do you set this var to nil?

dired-omit-extensions is a variable defined in ‘dired-x.el’.
Its value is
(".o" "~" ".bin" ".lbin" ".so" ".a" ".ln" ".blg" ".bbl" ".elc" ".lof" ".glo" ".idx" ".lot" ".svn/" ".hg/" ".git/" ".bzr/" "CVS/" "_darcs/" "_MTN/" ".fmt" ".tfm" ".class" ".fas" ".lib" ".mem" ".x86f" ".sparcf" ".dfsl" ".pfsl" ".d64fsl" ".p64fsl" ".lx64fsl" ".lx32fsl" ".dx64fsl" ".dx32fsl" ".fx64fsl" ".fx32fsl" ".sx64fsl" ".sx32fsl" ".wx64fsl" ".wx32fsl" ".fasl" ".ufsl" ".fsl" ".dxl" ".lo" ".la" ".gmo" ".mo" ".toc" ".aux" ".cp" ".fn" ".ky" ".pg" ".tp" ".vr" ".cps" ".fns" ".kys" ".pgs" ".tps" ".vrs" ".pyc" ".pyo" ".idx" ".lof" ".lot" ".glo" ".blg" ".bbl" ".cp" ".cps" ".fn" ".fns" ".ky" ".kys" ".pg" ".pgs" ".tp" ".tps" ".vr" ".vrs")

**Comment by abo-abo** [comment]
`dired-omit-files` completely overrides `dired-omit-extensions`. I adjust `dired-omit-files` to my personal use, e.g. I never have `.vrs` files, I don't ignore them.

**Comment by srustamo** [comment]
Thanks. Do you use ranger.el by any chance?

**Comment by abo-abo** [comment]
No.
