### ISSUE TITLE
I get some error

### ISSUE THREAD

**Issue by chenzhaobo** [abo-abo/oremacs#21]
Dear abo-abo:

 I am a beaginner. I got some problems and I can't fix them.

1、 I do` sudo apt-get install ispell aspell hunspell` ,but still get a error when start the emacs.
2、when I open a python file , there is not python completion. why and how I make it work ?
3、if I copy the whole oremacs folder to windows7 , can it work ? or how to install you configuration on windows7?

Here is my start error:
`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("," nil 0)
  split-string(nil "," t)
  ispell-parse-hunspell-affix-file(nil)
  ispell-find-hunspell-dictionaries()
  ispell-set-spellchecker-params()
  (progn (setq ispell-program-name "hunspell") (setq ispell-dictionary "en_US,nl_NL") (setq ispell-personal-dictionary (concat emacs-d "personal/ispell_dict")) (ispell-set-spellchecker-params) (ispell-hunspell-add-multi-dic "en_US,nl_NL"))
  (condition-case err (progn (setq ispell-program-name "hunspell") (setq ispell-dictionary "en_US,nl_NL") (setq ispell-personal-dictionary (concat emacs-d "personal/ispell_dict")) (ispell-set-spellchecker-params) (ispell-hunspell-add-multi-dic "en_US,nl_NL")) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "ispell" ":config" (error-message-string err)) :error))))
  (if (not (require (quote ispell) nil (quote t))) (ignore (message (format "Cannot load %s" (quote ispell)))) (condition-case err (progn (setq ispell-program-name "hunspell") (setq ispell-dictionary "en_US,nl_NL") (setq ispell-personal-dictionary (concat emacs-d "personal/ispell_dict")) (ispell-set-spellchecker-params) (ispell-hunspell-add-multi-dic "en_US,nl_NL")) ((debug error) (ignore (display-warning (quote use-package) (format "%s %s: %s" "ispell" ":config" (error-message-string err)) :error)))) t)
  eval-buffer(#<buffer  *load*-777469> nil "/home/czb/oremacs/init.el" nil t)  ; Reading at buffer position 9126
  load-with-code-conversion("/home/czb/oremacs/init.el" "/home/czb/oremacs/init.el" nil nil)
  load("/home/czb/oremacs/init.el" nil nil t)
  load-file("~/oremacs/init.el")
  eval-buffer(#<buffer  *load*> nil "/home/czb/.emacs.d/init.el" nil t)  ; Reading at buffer position 308
  load-with-code-conversion("/home/czb/.emacs.d/init.el" "/home/czb/.emacs.d/init.el" t t)
  load("/home/czb/.emacs.d/init" t t)
  #[0 "\205\266	\306=\203\307\310Q\202?	\311=\204\307\312Q\202?\313\307\314\315#\203*\316\202?\313\307\314\317#\203>\320\321\322!D\nB\323\202?\316\324\325\324\211#\210\324=\203e\326\327\330\307\331Q!\"\325\324\211#\210\324=\203d\210\203\247\332!\333\232\203\247\334!\211\335P\336!\203\201\211\202\214\336!\203\213\202\214\314\262\203\245\337\"\203\243\340\341#\210\342\343!\210\266\f?\205\264\314\325\344\324\211#)\262\207" [init-file-user system-type delayed-warnings-list user-init-file inhibit-default-init inhibit-startup-screen ms-dos "~" "/_emacs" windows-nt "/.emacs" directory-files nil "^\\.emacs\\(\\.elc?\\)?$" "~/.emacs" "^_emacs\\(\\.elc?\\)?$" initialization format-message "`_emacs' init file is deprecated, please use `.emacs'" "~/_emacs" t load expand-file-name "init" file-name-as-directory "/.emacs.d" file-name-extension "elc" file-name-sans-extension ".el" file-exists-p file-newer-than-file-p message "Warning: %s is newer than %s" sit-for 1 "default"] 7]()
  command-line()
  normal-top-level()
`

**Comment by abo-abo** [comment]
Which OS are you using? Did you follow these install steps?

```sh
git clone https://github.com/abo-abo/oremacs
cd oremacs
make install
make run
```

Other than that, I just removed the ispell config stuff, so that should not be an error any more.

**Comment by chenzhaobo** [comment]
I am using Deepin15.4 .
I do those install steps. after that ,I add `(load-file "~/oremacs/init.el")` to `~/.emacs.d/init.el`. and start emacs.

I pull the new commit.but  python completion  still not work.

there is an error in the message buffer:

`File mode specification error: (file-error Cannot open load file No such file or directory company-jedi)
Mark set`

the company-backends :
```
Its value is (company-elisp company-capf
               (company-dabbrev-code company-gtags company-etags company-keywords)
               company-files company-dabbrev)

Original value was 
(company-bbdb company-nxml company-css company-eclim company-semantic company-clang company-xcode company-cmake company-capf company-files
              (company-dabbrev-code company-gtags company-etags company-keywords)
              company-oddmuse company-dabbrev)
```

**Comment by abo-abo** [comment]
Please try again.

**Comment by chenzhaobo** [comment]
yes, python completion work now .
Thank you .
