### ISSUE TITLE
how to use keys.el

### ISSUE THREAD

**Issue by chenzhaobo** [abo-abo/oremacs#22]
Dear abo-abo

There are some keybind in keys.el , how to enter those keys ？Ｉ can't find them in my keyboard .
the kbd like this:
`(global-set-key (kbd "C-β") nil)                               ; [b]
(global-set-key (kbd "C-ν") 'ora-angles)                       ; [n]
(global-set-key (kbd "C-μ") 'headlong-bookmark-jump-other)     ; [m]
(global-set-key "υ" 'aya-expand)                             ; [y]
(global-set-key "ψ" 'universal-argument)                     ; [u]`
Thank you！

**Comment by abo-abo** [comment]
See this post: http://oremacs.com/2015/02/14/semi-xmodmap/.
Later, I'll add some customization to not load keys.el.

**Comment by chenzhaobo** [comment]
i am try to use the keybind. thank you!
