### ISSUE TITLE
Package installation: 'packages.el' vs 'ensure' keyword from `use-package' 

### ISSUE THREAD

**Issue by srustamo** [abo-abo/oremacs#23]
You seem to use both installation methods in the title. 

It also looks like you use `(setq use-package-always-ensure t)` somewhere (in `customize-group`, perhaps?), which is not visible in this repo.

How do you install the packages in `use-package`, which are not in 'packages.el'?

**Comment by abo-abo** [comment]
Grepping for `:ensure` I only see `ora-ido.el`, which I no longer use. So it's mainly `packages.el`. Sometimes I install things with `package-install` and promote them later to `package.el`.

**Comment by srustamo** [comment]
Thank you.
