### ISSUE TITLE
IRC in emacs

### ISSUE THREAD

**Issue by azzamsa** [abo-abo/oremacs#25]
Hi Abo-abo.

Sorry for asking this question. 
I just wonder how do you use IRC since I *think* you spend most of the time in Emacs.

I don't find any irc configuration here. (But I find gnus config which mean that you read email in emacs). Do you use other irc client rather than Emacs ?

Thank you. :)

**Comment by abo-abo** [comment]
Hi, I use <kbd>M-x</kbd> `erc` occasionally. Not too often to customize it. Most of my friends and colleagues don't use IRC, so I'm not there as well. Too bad, it's a nice open protocol.

**Comment by azzamsa** [comment]
Oh. Thank you for the answer :)

So it's mean you don't hang up often with foo-hackers and bar-hackers in IRC ?

**Comment by abo-abo** [comment]
No, (unfortunately?:). I guess I need to meet more people.

**Comment by azzamsa** [comment]
:)

Same here. Spent most of the time alone under the roof.

Thank you so much for your contribution to community.
Have a graet day. Abo-abo.
