### ISSUE TITLE
How to fold based on ;;* syntax

### ISSUE THREAD

**Issue by gcantieni** [abo-abo/oremacs#30]
Hi there, I enjoy how hand-crafted and minimal your config files are. It seems like you organize them not through whitespace but through hierarchical, org-like delimiters e.g. ;;* ;;** etc.

I imagine you must also make them fold visually. How do you do this? Is there some package you're using or is it a similarly hand-crafted solution?

**Comment by abo-abo** [comment]
I use [lispy](https://github.com/abo-abo/lispy) for this.

- enable `lispy-mode`
- put the point on `;;`
- press <kbd>i</kbd> to toggle one heading
- press <kbd>I</kbd> to toggle all headings
- press <kbd>C-u I</kbd> to make a table of contents

**Comment by gcantieni** [comment]
Thank you!
