### ISSUE TITLE
Wrong number of arguments: setq, 1 while doing ora-query-replace

### ISSUE THREAD

**Issue by mario-car** [abo-abo/oremacs#34]
When trying to do ora-query-replace I get error about wrong number of arguments:

Debugger entered--Lisp error: (wrong-number-of-arguments setq 1)
  (setq ora-qr-beg)
  (progn (goto-char ora-qr-beg) (setq ora-qr-beg))
  (if ora-qr-beg (progn (goto-char ora-qr-beg) (setq ora-qr-beg)))
  (ora-query-replace "def")
  (funcall-interactively ora-query-replace "def")
  (call-interactively ora-query-replace nil nil)
  (command-execute ora-query-replace)

**Comment by abo-abo** [comment]
Thanks, should be fixed now. I haven't used that function in a while, since I use the following combo: <kbd>C-s M-n M-q</kbd>, which uses `swiper-isearch` and is a little bit more visual.
