### ISSUE TITLE
How to switch C-h back to C-p?

### ISSUE THREAD

**Issue by toinfty** [abo-abo/oremacs#7]
Dear abo-abo, 

I watched some of your Youtube videos and then come to your configurations from the vanilla emacs. I am not quite used to the `C-h` in your configuration, is there any switch in your configuration to map `C-h` back to `C-p` ?

Best,

**Comment by abo-abo** [comment]
You can do it like this:

```elisp
(keyboard-translate ?\C-h ?\C-h)
(keyboard-translate ?\C-p ?\C-p)
```

**Comment by toinfty** [comment]
I add the two lines to `keys.el`. It works! Thanks, I learn something new!
